version: "3"

x-base: &base #
  image: harbor.timeresearch.biz/onchain/gcs_transfer:0.0.1
  # image: ab
  environment:
    - PYTHONPATH=/root/gcs_transfer/:$PYTHONPATH
  network_mode: host
  ipc: host
  restart: always

services:
  gcs_transfer:
    container_name: gcs_transfer
    <<: *base
    pull_policy: always
    environment:
      GCP_KEY_PATH: /root/gcs_transfer/gcp_key.json
      GOOGLE_APPLICATION_CREDENTIALS: /root/gcs_transfer/gcp_key.json
      TABLES: defi.all_label_address,defi.total_marking_address
      LARK_URL: https://open.larksuite.com/open-apis/bot/v2/hook/4e48a198-8bfa-4d8e-a83a-e2487a24f730
      UPDATE_INTERVAL_MINUTES: 15
      uploading: 1.0
    command: |
      /usr/bin/python3 /root/gcs_transfer/main.py
